export const SET_DATES_RANGE = 'SET_DATES_RANGE';
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_EXCHANGE_DATA = 'SET_EXCHANGE_DATA';
export const SET_TODAY_DATA = 'SET_TODAY_DATA';
export const SORT_TABLE = 'SORT_TABLE';
export const SET_REST_COUNTRIES = 'SET_REST_COUNTRIES';
export const SET_DISPLAY_COUNTRIES_MODAL = 'SET_DISPLAY_COUNTRIES_MODAL';
export const SET_DATA_COUNTRIES_MODAL = 'SET_DATA_COUNTRIES_MODAL';

