//Toolbar
export const TOOLBAR_SHOW_CHART = 'TOOLBAR_SHOW_CHART';
export const TOOLBAR_SHOW_TABLE = 'TOOLBAR_SHOW_TABLE';
//Chart
export const SET_DATES_RANGE = 'SET_DATES_RANGE';
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_EXCHANGE_DATA = 'SET_EXCHANGE_DATA';
//Table
export const SET_TODAY_DATA = 'SET_TODAY_DATA';
export const SORT_TABLE = 'SORT_TABLE';
export const SET_REST_COUNTRIES = 'SET_REST_COUNTRIES';
export const VISIBILITY_COUNTRIES_INFO = 'VISIBILITY_COUNTRIES_INFO';
export const SET_DATA_COUNTRIES_INFO = 'SET_DATA_COUNTRIES_INFO';
